### ISSUE TITLE
checkpoint of ped2 missing

### ISSUE THREAD

**Issue by Kazaf-Li** [ChangYunPeng/VideoAnomalyDetection#5]
Hi, first of alll thanks for your work, and i encounter a problem so far, the checkpoints of the dataset ped2 is unavailable for now, can you plz upload a new link ? mank thanks

**Comment by Kazaf-Li** [comment]
my mistake, i have already solved it

**Comment by momoko31** [comment]
may I ask how to get the checkpoints? because now the author's link failure
